import os
import sys

# Force absolute search paths to isolate correct project files
current_project_dir = r"C:\fish_w_estimator\backend"
if current_project_dir not in sys.path:
    sys.path.insert(0, current_project_dir)

import io
import base64
import cv2
import numpy as np
import torch
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# Import your working backend runner class directly
from source_code.inference import FishWeightPredictor

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    # Use standard initialization matching the backend execution defaults
    predictor = FishWeightPredictor()
except Exception as e:
    print(f"Error loading models: {e}")
    predictor = None

@app.post("/predict")
async def predict_fish_weight(
    image: UploadFile = File(...),
    cm_per_pixel: float = Form(0.038)
):
    if not predictor:
        raise HTTPException(status_code=500, detail="AI Models are not initialized on server.")

    try:
        # 1. Read incoming browser stream bytes
        contents = await image.read()
        
        # 2. Write file directly to workspace disk
        temp_path = os.path.join(current_project_dir, "temp_web_upload.jpg")
        with open(temp_path, "wb") as f:
            f.write(contents)

        # 3. RUN THE EXACT UNTOUCHED BACKEND METHOD
        # We call predictor.predict() directly on the file path.
        # This guarantees that the exact same load_image() and copyMakeBorder()
        # functions execute precisely how they did in your standalone script!
        predictor.cm_per_pixel = cm_per_pixel
        results = predictor.predict(temp_path)

        # 4. Extract the mask matrix generated by your working script
        mask_2d = results['mask']
        
        # 5. Base64 Encode the array back to the web view layout
        mask_u8 = (mask_2d * 255).astype(np.uint8)
        _, buffer = cv2.imencode('.png', mask_u8)
        base64_mask = base64.b64encode(buffer).decode('utf-8')
        generated_mask_url = f"data:image/png;base64,{base64_mask}"

        # Clean up disk workspace
        if os.path.exists(temp_path):
            os.remove(temp_path)

        return {
            "predicted_weight_g": results["predicted_weight_g"],
            "features": {
                "length_cm": results["features"]["length_cm"],
                "thickness_cm": results["features"]["thickness_cm"],
                "perimeter_cm": results["features"]["perimeter_cm"],
                "area_cm2": results["features"]["area_cm2"],
                "volume_proxy_cm3": results["features"]["volume_proxy_cm3"],
            },
            "generated_mask": generated_mask_url
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))